
await page.locator('button').filter({ hasText: 'Import Excel' }).click();
const download4Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Template' }).click();
  const download4 = await download4Promise;
await page.getByRole('button', { name: 'Close' }).click();
await page.locator('.dropdown-toggle.btn.btn-sm.dropdown.arrow-none.d-block.py-0.px-2.text-info').click();
await page.getByText('Dummy List').click();
await page.getByRole('textbox').nth(1).click();
await page.getByRole('textbox').nth(1).fill('salman');
await page.getByRole('button', { name: 'Save' }).click();
await expect(page.getByRole('paragraph')).toContainText('Guest(s) reservation successfull.');
await page.getByRole('button', { name: 'OK' }).click();
await page.locator('.dropdown-toggle.btn.btn-sm.dropdown.arrow-none.d-block.py-0.px-2.text-info').click();
await page.getByText('Rate Plan').click();
await page.getByRole('button', { name: 'OK' }).click();
await page.getByRole('button', { name: 'Close' }).click();
await page.getByLabel('Show CX/NS also').check();
await page.locator('icon-button-control:nth-child(6) > .btn').click();
await page.locator('button').filter({ hasText: 'Import Excel' }).click();
const download5Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download Template' }).click();
  const download5 = await download5Promise;
await page.getByRole('button', { name: 'Browse for file' }).click();
await page.getByRole('button', { name: 'Browse for file' }).setInputFiles('ReservationTemplate (2).xlsx');
await page.getByRole('button', { name: 'Upload' }).click();
await page.getByRole('button', { name: 'Close' }).click();
await page.locator('icon-button-control:nth-child(6) > .btn').click();
await page.locator('input[name="checkAllfolio"]').check();
await page.getByText('Auto Assign Room').click();
await expect(page.getByRole('paragraph')).toContainText('Rooms Allocated.');
await page.getByRole('button', { name: 'OK' }).click();

await page.getByText('Auto Assign Room').click();
await expect(page.getByRole('paragraph')).toContainText('ROOM ALREADY EXISTS/ASSIGNED (757)');
await page.getByRole('button', { name: 'OK' }).click();
await page.getByText('Checkin', { exact: true }).click();
await expect(page.getByRole('paragraph')).toContainText('Group is not In-house');
await page.getByRole('button', { name: 'OK' }).click();
await page.locator('dropdown-button:nth-child(6) > .d-flex > .flex-shrink-0 > div > .dropdown-toggle').click();
await page.getByText('Checkin Group').click();
await expect(page.getByRole('paragraph')).toContainText('Are you Sure You Want To Checkin');
await page.getByRole('button', { name: 'Yes' }).click();
await expect(page.getByRole('paragraph')).toContainText('Group Checked In.');
await page.getByRole('button', { name: 'OK' }).click();
await page.locator('dropdown-button:nth-child(6) > .d-flex > .flex-shrink-0 > div > .dropdown-toggle').click();
await page.getByText('Process Checkout').click();
await expect(page.getByRole('paragraph')).toContainText('Are you sure you want to check out the Group ?');
await page.getByRole('button', { name: 'Yes' }).click();
await expect(page.getByRole('paragraph')).toContainText('You cannot check out this group because some of the guests are already confirmed.');
await page.getByRole('button', { name: 'OK' }).click();
await page.locator('dropdown-button:nth-child(6) > .d-flex > .flex-shrink-0 > div > .dropdown-toggle').click();
await page.locator('.show > .dropdown-toggle').click();

await page.getByText('Sections').click();
await page.getByText('Download Details').click();
await page.getByRole('row', { name: 'Guest Id Room Type Name Status' }).getByLabel('', { exact: true }).check();
await page.getByRole('row', { name: 'Download For Value' }).getByLabel('', { exact: true }).check();
await page.getByRole('button', { name: 'Save' }).click();
await expect(page.getByRole('paragraph')).toContainText('Download Successful.');
await page.getByRole('button', { name: 'OK' }).click();
await page.getByText('No Show').click();
await expect(page.getByRole('paragraph')).toContainText('Details created/updated successfully.');
await page.getByRole('button', { name: 'OK' }).click();
await page.getByText('Cancel Confirm').click();
await page.getByRole('combobox').click();
await page.getByRole('combobox').getByRole('textbox').press('ArrowDown');
await page.getByRole('combobox').getByRole('textbox').press('Enter');
await page.locator('textarea').click();
await page.locator('textarea').fill('unknown');
await page.getByRole('button', { name: 'Ok' }).click();
await expect(page.getByRole('paragraph')).toContainText('Details created/updated successfully.');
await page.getByRole('button', { name: 'OK' }).click();
await page.locator('.ng-star-inserted > .btn').first().click();
await page.locator('.ng-star-inserted > .btn').first().click();
